<?php

//we use void channel to denote the user has deleted all channels. which is really not very useful.. 
class ChannelsTableSeeder extends Seeder {

	public function run()
	{
		$channels = array( 
			array('name'=>'void_channel', 'id'=>0, 'logo'=>'nil','category'=>'nil'),
			array('name'=>'9X','id'=>84,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/9x.png','category'=>'entertainment'),
			array('name'=>'Amrita Tv','id'=>205,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Amrita-Tv.png','category'=>'entertainment'),
			array('name'=>'Anjan Tv','id'=>376,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Anjan-Tv.png','category'=>'entertainment'),
			array('name'=>'Asianet','id'=>153,'logo'=>'http://tvimages.burrp.com/images/channels1/Entertainment/Asianet.png','category'=>'entertainment'),
			array('name'=>'Asianet Plus','id'=>157,'logo'=>'http://tvimages.burrp.com/images/channels1/Entertainment/Asianet-Plus.png','category'=>'entertainment'),
			array('name'=>'Asianet Suvarna','id'=>165,'logo'=>'http://tvimages.burrp.com/images/channels1/Entertainment/Asianet-Suvarna.png','category'=>'entertainment'),
			array('name'=>'AXN','id'=>1,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/axn.png','category'=>'entertainment'),
			array('name'=>'Big CBS Love','id'=>219,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Big-CBS-Love.png','category'=>'entertainment'),
			array('name'=>'Big CBS Prime','id'=>213,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Prime.png','category'=>'entertainment'),
			array('name'=>'Big Magic','id'=>357,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Big-Magic.png','category'=>'entertainment'),
			array('name'=>'BIG RTL Thrill','id'=>288,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/BIG-RTL-Thrill.png','category'=>'entertainment'),
			array('name'=>'Bindass','id'=>75,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Bindass.png','category'=>'entertainment'),
			array('name'=>'Bindass Play','id'=>253,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/BP.png','category'=>'entertainment'),
			array('name'=>'Channel [V]','id'=>81,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Channel-[V].png','category'=>'entertainment'),
			array('name'=>'Colors','id'=>66,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/colors.png','category'=>'entertainment'),
			array('name'=>'Dabangg TV','id'=>297,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Dabangg-TV.png','category'=>'entertainment'),
			array('name'=>'Dhamaal TV','id'=>298,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Dhamaal-TV.png','category'=>'entertainment'),
			array('name'=>'DY 365','id'=>340,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/DY-365.png','category'=>'entertainment'),
			array('name'=>'E 24','id'=>184,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/e24.png','category'=>'entertainment'),
			array('name'=>'Etv','id'=>120,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/etv.png','category'=>'entertainment'),
			array('name'=>'Firangi','id'=>255,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/firangi.png','category'=>'entertainment'),
			array('name'=>'Fox Crime','id'=>168,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Fox-Crime.png','category'=>'entertainment'),
			array('name'=>'Fox Life','id'=>83,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Fox-Life.png','category'=>'entertainment'),
			array('name'=>'Fox Life HD','id'=>504,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Fox-Life-HD.png','category'=>'entertainment'),
			array('name'=>'FX','id'=>169,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/FX.png','category'=>'entertainment'),
			array('name'=>'Gemini Tv','id'=>137,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Gemini-Tv.png','category'=>'entertainment'),
			array('name'=>'Gemini Tv HD','id'=>497,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Gemini-Tv-HD.png','category'=>'entertainment'),
			array('name'=>'Imayam Tv','id'=>263,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Imayam.png','category'=>'entertainment'),
			array('name'=>'Jan TV','id'=>344,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Jan-TV.png','category'=>'entertainment'),
			array('name'=>'Jaya Max','id'=>149,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Jaya-Max.png','category'=>'entertainment'),
			array('name'=>'Jaya Plus','id'=>148,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Jaya-Plus.png','category'=>'entertainment'),
			array('name'=>'Jaya Tv','id'=>147,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Jaya-Tv_.png','category'=>'entertainment'),
			array('name'=>'Jeevan Tv','id'=>279,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Jeevan-Tv.png','category'=>'entertainment'),
			array('name'=>'Kairali Tv','id'=>197,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Kairali-Tv.png','category'=>'entertainment'),
			array('name'=>'Kalaignar Chithiram','id'=>215,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Kalaignar-Chithiram.png','category'=>'entertainment'),
			array('name'=>'Kalaignar Sirippoli','id'=>191,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Kalaignar-Sirippoli.png','category'=>'entertainment'),
			array('name'=>'Kalaignar Tv','id'=>189,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Kalaignar.png','category'=>'entertainment'),
			array('name'=>'Kasthuri TV','id'=>500,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Kasthuri-TV.PNG','category'=>'entertainment'),
			array('name'=>'Khushboo Tv','id'=>437,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Khushboo-Tv.png','category'=>'entertainment'),
			array('name'=>'Life Ok','id'=>259,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Life-Ok.png','category'=>'entertainment'),
			array('name'=>'Life Ok HD','id'=>358,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Life-Ok-HD.png','category'=>'entertainment'),
			array('name'=>'Maa Gold','id'=>274,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Maa-Gold.png','category'=>'entertainment'),
			array('name'=>'Maa Tv','id'=>247,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Maa-Tv.png','category'=>'entertainment'),
			array('name'=>'Mahuaa Tv','id'=>507,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Mahuaa-Tv.png','category'=>'entertainment'),
			array('name'=>'Mega TV','id'=>499,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Mega-TV.png','category'=>'entertainment'),
			array('name'=>'Polimer Tv','id'=>352,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Polimer-Tv.png','category'=>'entertainment'),
			array('name'=>'Raj Tv','id'=>144,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Raj-Tv.png','category'=>'entertainment'),
			array('name'=>'Ruposhi Bangla','id'=>490,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Ruposhi-Bangla.png','category'=>'entertainment'),
			array('name'=>'Saam TV','id'=>350,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Saam-TV.png','category'=>'entertainment'),
			array('name'=>'Sada Channel','id'=>356,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Sada-Channel.png','category'=>'entertainment'),
			array('name'=>'Sahara One','id'=>89,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Sahara-One.png','category'=>'entertainment'),
			array('name'=>'Sony Entertainment TV','id'=>78,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Sony-Entertainment-TV.png','category'=>'entertainment'),
			array('name'=>'Sony Pal','id'=>522,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Sony-Pal.png','category'=>'entertainment'),
			array('name'=>'Sony SAB','id'=>77,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Sony-SAB.png','category'=>'entertainment'),
			array('name'=>'Sony TV HD','id'=>506,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Sony-Entertainment-TV-HD.png','category'=>'entertainment'),
			array('name'=>'Star Jalsha','id'=>119,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/star-jalsha.png','category'=>'entertainment'),
			array('name'=>'Star Plus','id'=>29,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/star-plus.png','category'=>'entertainment'),
			array('name'=>'Star Plus HD','id'=>239,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Star-Plus-HD.png','category'=>'entertainment'),
			array('name'=>'Star Pravah','id'=>131,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Star-Pravah.png','category'=>'entertainment'),
			array('name'=>'Star Utsav','id'=>30,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/utsav.png','category'=>'entertainment'),
			array('name'=>'Star Vijay','id'=>164,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Star-Vijay.png','category'=>'entertainment'),
			array('name'=>'Star World','id'=>23,'logo'=>'http://tvimages.burrp.com/images/channels1/Entertainment/Star-World.png','category'=>'entertainment'),
			array('name'=>'Star World HD','id'=>241,'logo'=>'http://tvimages.burrp.com/images/channels1/Entertainment/Star-World-HD.png','category'=>'entertainment'),
			array('name'=>'Star World Premier HD','id'=>515,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Star-World-Premiere-HD.png','category'=>'entertainment'),
			array('name'=>'Sun Tv','id'=>152,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Sun-Tv.png','category'=>'entertainment'),
			array('name'=>'Sun Tv HD','id'=>508,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Sun-Tv-HD.png','category'=>'entertainment'),
			array('name'=>'Surya Tv','id'=>136,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/surya-tv.png','category'=>'entertainment'),
			array('name'=>'Suvarna Plus','id'=>460,'logo'=>'http://tvimages.burrp.com/images/channels1/Entertainment/Suvarna-Plus.png','category'=>'entertainment'),
			array('name'=>'Udaya','id'=>134,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/udaya-tv.png','category'=>'entertainment'),
			array('name'=>'Zee Cafe','id'=>65,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Zee-Cafe.png','category'=>'entertainment'),
			array('name'=>'Zee Kannada','id'=>272,'logo'=>'http://tvimages.burrp.com/images/channels1/Entertainment/Zee-Kannada.png','category'=>'entertainment'),
			array('name'=>'Zee Smile','id'=>155,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Zee-Smile.png','category'=>'entertainment'),
			array('name'=>'Zee Telugu','id'=>292,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Zee-Telugu.png','category'=>'entertainment'),
			array('name'=>'ZEE TV','id'=>32,'logo'=>'http://tvimages.burrp.com/images/channels1/Entertainment/ZEE-TV.png','category'=>'entertainment'),
			array('name'=>'Zee TV HD','id'=>438,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Zee-TV-HD.png','category'=>'entertainment'),
			array('name'=>'Zindagi','id'=>520,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/zee-Zindagi.png','category'=>'entertainment'),
			array('name'=>'Zing','id'=>109,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/Zing.png','category'=>'entertainment'),
			array('name'=>'Zoom','id'=>20,'logo'=>'http://tvimages.burrp.com/images/channels1/entertainment/zoom.png','category'=>'entertainment'),

			array('name'=>'Asianet Movies','id'=>271,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/asianet-movies.png','category'=>'movies'),
			array('name'=>'B4U Movies','id'=>88,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/b4umovies.png','category'=>'movies'),
			array('name'=>'Cinema TV','id'=>280,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/cinema%20tv.png','category'=>'movies'),
			array('name'=>'FILMY','id'=>82,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/filmy.png','category'=>'movies'),
			array('name'=>'Gemini Movies','id'=>185,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/gemini%20movies_.png','category'=>'movies'),
			array('name'=>'HBO','id'=>8,'logo'=>'http://tvimages.burrp.com/images/channels1/Movies/HBO.png','category'=>'movies'),
			array('name'=>'HBO Defined','id'=>286,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/Def.png','category'=>'movies'),
			array('name'=>'HBO Hits','id'=>285,'logo'=>'http://tvimages.burrp.com/images/channels1/Movies/HBO-Hits.png','category'=>'movies'),
			array('name'=>'India Talkies','id'=>199,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/India-Talkies_.png','category'=>'movies'),
			array('name'=>'Jaya Movie','id'=>221,'logo'=>'http://tvimages.burrp.com/images/channels1/Movies/J-Movie.png','category'=>'movies'),
			array('name'=>'Kiran Tv','id'=>145,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/kirantv.png','category'=>'movies'),
			array('name'=>'KTV','id'=>162,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/ktv_.png','category'=>'movies'),
			array('name'=>'Ktv HD','id'=>502,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/ktvHD_.png','category'=>'movies'),
			array('name'=>'Maa Movies','id'=>231,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/maamovies_.png','category'=>'movies'),
			array('name'=>'MGM','id'=>95,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/MGM.png','category'=>'movies'),
			array('name'=>'Movies Now','id'=>207,'logo'=>'http://tvimages.burrp.com/images/channels1/Movies/movies-now.png','category'=>'movies'),
			array('name'=>'Movies Ok','id'=>270,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/movies-ok.png','category'=>'movies'),
			array('name'=>'Raj Digital Plus','id'=>161,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/Raj-Digital-Plus.png','category'=>'movies'),
			array('name'=>'Romedy Now','id'=>482,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/romedy-now.png','category'=>'movies'),
			array('name'=>'Sony MAX','id'=>51,'logo'=>'http://tvimages.burrp.com/images/channels1/Movies/Sony-Max.png','category'=>'movies'),
			array('name'=>'Sony Max 2','id'=>523,'logo'=>'http://tvimages.burrp.com/images/ch/8/q/8q8kle1i_ej_2.gif','category'=>'movies'),
			array('name'=>'Sony PIX','id'=>53,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/sonypix.png','category'=>'movies'),
			array('name'=>'Star Gold','id'=>64,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/stargold.png','category'=>'movies'),
			array('name'=>'Star Gold HD','id'=>243,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/stargoldHD.png','category'=>'movies'),
			array('name'=>'Star Movies','id'=>59,'logo'=>'http://tvimages.burrp.com/images/channels1/Movies/Star-Movies.png','category'=>'movies'),
			array('name'=>'Star Movies Action','id'=>284,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/Star-Movies-Action.png','category'=>'movies'),
			array('name'=>'Star Movies HD','id'=>245,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/Star-Movies-HD.png','category'=>'movies'),
			array('name'=>'Udaya Movies','id'=>140,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/Udaya-Movies.png','category'=>'movies'),
			array('name'=>'UTV Action','id'=>73,'logo'=>'http://tvimages.burrp.com/images/channels1/Movies/UTV-Action.png','category'=>'movies'),
			array('name'=>'UTV Movies','id'=>76,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/utv-movies.png','category'=>'movies'),
			array('name'=>'WB','id'=>99,'logo'=>'http://tvimages.burrp.com/images/channels1/Movies/WB.png','category'=>'movies'),
			array('name'=>'World Movies','id'=>74,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/World-Movies.png','category'=>'movies'),
			array('name'=>'Zee Action','id'=>90,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/zee-action_.png','category'=>'movies'),
			array('name'=>'Zee Cinema','id'=>4,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/Zee-Cinema.png','category'=>'movies'),
			array('name'=>'Zee Classic','id'=>92,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/zee-classic.png','category'=>'movies'),
			array('name'=>'Zee Premier','id'=>91,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/Zee-Premier.png','category'=>'movies'),
			array('name'=>'Zee Studio','id'=>63,'logo'=>'http://tvimages.burrp.com/images/channels1/Movies/Zee-Studio.png','category'=>'movies'),
			array('name'=>'Zee Talkies','id'=>132,'logo'=>'http://tvimages.burrp.com/images/channels1/movies/Zee-Talkies.png','category'=>'movies'),

			array('name'=>'Adithya TV','id'=>299,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Adithya-TV.png','category'=>'kids'),
			array('name'=>'Animax','id'=>57,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/animax.png','category'=>'kids'),
			array('name'=>'Baby TV','id'=>315,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Baby-TV.png','category'=>'kids'),
			array('name'=>'Cartoon Network','id'=>3,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/cartoon-network.png','category'=>'kids'),
			array('name'=>'Chintu Tv','id'=>150,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Chintu-Tv.png','category'=>'kids'),
			array('name'=>'Chutti TV','id'=>112,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Chutti-TV.png','category'=>'kids'),
			array('name'=>'Discovery Kids','id'=>291,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Discovery-Kids.png','category'=>'kids'),
			array('name'=>'Disney Channel','id'=>93,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Disney-Channel.png','category'=>'kids'),
			array('name'=>'Disney XD','id'=>96,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Disney-XD.png','category'=>'kids'),
			array('name'=>'Hungama TV','id'=>130,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Hungama-TV.png','category'=>'kids'),
			array('name'=>'Kochu Tv','id'=>278,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Kochu-Tv.png','category'=>'kids'),
			array('name'=>'Kushi Tv','id'=>151,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Kushi-Tv.png','category'=>'kids'),
			array('name'=>'Nick Junior','id'=>294,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Nick-Junior.png','category'=>'kids'),
			array('name'=>'Nickelodeon','id'=>79,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Nickelodeon.png','category'=>'kids'),
			array('name'=>'POGO','id'=>58,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/pogo.png','category'=>'kids'),
			array('name'=>'Sonic','id'=>293,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Sonic.png','category'=>'kids'),
			array('name'=>'Topper TV','id'=>341,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/Topper-TV.png','category'=>'kids'),
			array('name'=>'ZeeQ','id'=>273,'logo'=>'http://tvimages.burrp.com/images/channels1/kids/ZeeQ.png','category'=>'kids'),

			array('name'=>'Animal Planet','id'=>45,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/Animal-planet.png','category'=>'documentary'),
			array('name'=>'Discovery Channel','id'=>46,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/Discovery-Channel.png','category'=>'documentary'),
			array('name'=>'Discovery HD','id'=>182,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/Discovery-HD.png','category'=>'documentary'),
			array('name'=>'Discovery Science','id'=>172,'logo'=>'http://tvimages.burrp.com/images/channels1/Documentary/Discovery-Science.png','category'=>'documentary'),
			array('name'=>'Discovery Tamil','id'=>364,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/Discovery-Tamil.png','category'=>'documentary'),
			array('name'=>'Discovery Turbo','id'=>171,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/Discovery-Turbo.png','category'=>'documentary'),
			array('name'=>'History Tv 18','id'=>265,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/History-Tv-18.png','category'=>'documentary'),
			array('name'=>'Nat Geo People','id'=>173,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/Nat-Geo-People.png','category'=>'documentary'),
			array('name'=>'Nat Geo People HD','id'=>498,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/Nat-Geo-People-HD.png','category'=>'documentary'),
			array('name'=>'Nat Geo Wild','id'=>180,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/Nat-Geo-Wild.png','category'=>'documentary'),
			array('name'=>'National Geographic Channel','id'=>71,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/National-Geographic-Channel.png','category'=>'documentary'),
			array('name'=>'National Geographic Channel HD','id'=>181,'logo'=>'http://tvimages.burrp.com/images/channels1/documentary/National-Geographic-Channel-HD.png','category'=>'documentary'),

			array('name'=>'7 S Music','id'=>379,'logo'=>'http://tvimages.burrp.com/images/channels1/music/7-S-Music.png','category'=>'music'),
			array('name'=>'9X Jalwa','id'=>277,'logo'=>'http://tvimages.burrp.com/images/channels1/music/9x-jalwa.png','category'=>'music'),
			array('name'=>'9X Jhakaas','id'=>276,'logo'=>'http://tvimages.burrp.com/images/channels1/music/9X-Jhakaas.png','category'=>'music'),
			array('name'=>'9X Tashan','id'=>371,'logo'=>'http://tvimages.burrp.com/images/channels1/music/9X-Tashan.png','category'=>'music'),
			array('name'=>'9XM','id'=>104,'logo'=>'http://tvimages.burrp.com/images/channels1/music/9XM.png','category'=>'music'),
			array('name'=>'9xO','id'=>295,'logo'=>'http://tvimages.burrp.com/images/channels1/music/9xO.png','category'=>'music'),
			array('name'=>'B4U Music','id'=>87,'logo'=>'http://tvimages.burrp.com/images/channels1/music/b4u-music.png','category'=>'music'),
			array('name'=>'Dhoom Music','id'=>318,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Dhoom-Music.png','category'=>'music'),
			array('name'=>'Gemini Music','id'=>139,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Gemini-Music.png','category'=>'music'),
			array('name'=>'Kalaignar Isai Aruvi','id'=>193,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Kalaignar-Isai-Aruvi.png','category'=>'music'),
			array('name'=>'Kalaignar Murasu','id'=>505,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Kalaignar-Murasu.png','category'=>'music'),
			array('name'=>'Maa Music','id'=>235,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Maa-Music.png','category'=>'music'),
			array('name'=>'Mastiii','id'=>237,'logo'=>'http://tvimages.burrp.com/images/channels1/music/mastiii.png','category'=>'music'),
			array('name'=>'Mega Musiq','id'=>360,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Mega-Musiq.png','category'=>'music'),
			array('name'=>'Mtunes','id'=>339,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Mtunes.png','category'=>'music'),
			array('name'=>'Mtunes HD','id'=>331,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Mtunes-HD.png','category'=>'music'),
			array('name'=>'MTV','id'=>9,'logo'=>'http://tvimages.burrp.com/images/channels1/music/mtv.png','category'=>'music'),
			array('name'=>'Music India','id'=>203,'logo'=>'http://tvimages.burrp.com/images/channels1/music/music-india.png','category'=>'music'),
			array('name'=>'Music Xpress','id'=>365,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Music-Xpress.png','category'=>'music'),
			array('name'=>'Nat Geo Music','id'=>217,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Nat-Geo-Music.png','category'=>'music'),
			array('name'=>'PTC Chak De','id'=>354,'logo'=>'http://tvimages.burrp.com/images/channels1/music/PTC-Chak-De.png','category'=>'music'),
			array('name'=>'Raj Music Karnataka','id'=>481,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Raj-Music-Karnataka.png','category'=>'music'),
			array('name'=>'Raj Musix','id'=>163,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Raj-Musix.png','category'=>'music'),
			array('name'=>'Raj Musix Telugu','id'=>418,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Raj-Musix-Telugu.png','category'=>'music'),
			array('name'=>'Sangeet Bangla','id'=>229,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Sangeet-Bangla.png','category'=>'music'),
			array('name'=>'Sangeet Bhojpuri','id'=>227,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Sangeet-Bhojpuri.png','category'=>'music'),
			array('name'=>'Sony Mix','id'=>296,'logo'=>'http://tvimages.burrp.com/images/channels1/music/sony-mix.png','category'=>'music'),
			array('name'=>'SS Music','id'=>373,'logo'=>'http://tvimages.burrp.com/images/channels1/music/SS-Music.png','category'=>'music'),
			array('name'=>'Sun Music','id'=>308,'logo'=>'http://tvimages.burrp.com/images/channels1/music/sun-music.png','category'=>'music'),
			array('name'=>'Tarang Music','id'=>319,'logo'=>'http://tvimages.burrp.com/images/channels1/music/tarang-music.png','category'=>'music'),
			array('name'=>'Udaya Music','id'=>310,'logo'=>'http://tvimages.burrp.com/images/channels1/music/Udaya-Music.png','category'=>'music'),
			array('name'=>'Vh1','id'=>80,'logo'=>'http://tvimages.burrp.com/images/channels1/music/vh1.png','category'=>'music'),
			array('name'=>'Z etc','id'=>113,'logo'=>'http://tvimages.burrp.com/images/channels1/music/z-etc.png','category'=>'music'),

			array('name'=>'Aaj Tak','id'=>290,'logo'=>'http://tvimages.burrp.com/images/channels1/News/Aaj-Tak.png','category'=>'news'),
			array('name'=>'Asianet News','id'=>166,'logo'=>'http://tvimages.burrp.com/images/channels1/news/Asianet-News.png','category'=>'news'),
			array('name'=>'BBC World News','id'=>85,'logo'=>'http://tvimages.burrp.com/images/channels1/news/BBC-World-News.png','category'=>'news'),
			array('name'=>'Captain News','id'=>317,'logo'=>'http://tvimages.burrp.com/images/channels1/news/Captain-News.png','category'=>'news'),
			array('name'=>'CNBC AWAAZ','id'=>110,'logo'=>'http://tvimages.burrp.com/images/channels1/news/cnbc-awaaz.png','category'=>'news'),
			array('name'=>'CNBC Bajar','id'=>519,'logo'=>'http://tvimages.burrp.com/images/channels1/news/CNBC-Bajar.png','category'=>'news'),
			array('name'=>'CNBC TV18','id'=>106,'logo'=>'http://tvimages.burrp.com/images/channels1/news/CNBC-TV18.png','category'=>'news'),
			array('name'=>'CNBC TV18 Prime HD','id'=>516,'logo'=>'http://tvimages.burrp.com/images/channels1/news/CNBC-TV18-Prime-HD.png','category'=>'news'),
			array('name'=>'CNN','id'=>86,'logo'=>'http://tvimages.burrp.com/images/channels1/news/CNN.png','category'=>'news'),
			array('name'=>'CNN-IBN','id'=>50,'logo'=>'http://tvimages.burrp.com/images/channels1/news/CNN-IBN.png','category'=>'news'),
			array('name'=>'IBN 7','id'=>111,'logo'=>'http://tvimages.burrp.com/images/channels1/news/IBN-7.png','category'=>'news'),
			array('name'=>'IBN Lokmat','id'=>108,'logo'=>'http://tvimages.burrp.com/images/channels1/news/IBN-Lokmat.png','category'=>'news'),
			array('name'=>'NDTV 24X7','id'=>158,'logo'=>'http://tvimages.burrp.com/images/channels1/news/NDTV-24X7.png','category'=>'news'),
			array('name'=>'NDTV India','id'=>160,'logo'=>'http://tvimages.burrp.com/images/channels1/news/NDTV-India.png','category'=>'news'),
			array('name'=>'NDTV Profit','id'=>159,'logo'=>'http://tvimages.burrp.com/images/channels1/news/NDTV-Profit.png','category'=>'news'),
			array('name'=>'Raj News 24x7','id'=>346,'logo'=>'http://tvimages.burrp.com/images/channels1/news/Raj-News-24x7.png','category'=>'news'),
			array('name'=>'Raj News Malyalam','id'=>419,'logo'=>'http://tvimages.burrp.com/images/channels1/news/Raj-News-Malayalam.png','category'=>'news'),
			array('name'=>'Seithigal','id'=>311,'logo'=>'http://tvimages.burrp.com/images/channels1/news/Seithigal.png','category'=>'news'),
			array('name'=>'Sun News','id'=>309,'logo'=>'http://tvimages.burrp.com/images/channels1/news/sun-news.png','category'=>'news'),
			array('name'=>'Suvarna News 24x7','id'=>348,'logo'=>'http://tvimages.burrp.com/images/channels1/news/Suvarna-News-24x7.png','category'=>'news'),
			array('name'=>'Times Now','id'=>127,'logo'=>'http://tvimages.burrp.com/images/channels1/news/Times-Now.png','category'=>'news'),
			array('name'=>'Udaya News','id'=>313,'logo'=>'http://tvimages.burrp.com/images/channels1/news/udaya-news.png','category'=>'news'),
			array('name'=>'Zee Business','id'=>2,'logo'=>'http://tvimages.burrp.com/images/channels1/news/Zee-Business.png','category'=>'news'),
			array('name'=>'Zee News','id'=>287,'logo'=>'http://tvimages.burrp.com/images/channels1/news/Zee-News.png','category'=>'news'),

			array('name'=>'Adhyatma TV','id'=>347,'logo'=>'http://tvimages.burrp.com/images/channels1/spiritual/adhyatma-tv.png','category'=>'devotional'),
			array('name'=>'Angel Tv','id'=>156,'logo'=>'http://tvimages.burrp.com/images/channels1/spiritual/Angel-Tv.png','category'=>'devotional'),
			array('name'=>'Arihant Tv','id'=>337,'logo'=>'http://tvimages.burrp.com/images/channels1/spiritual/Arihant-Tv.png','category'=>'devotional'),
			array('name'=>'Aseervatham TV','id'=>321,'logo'=>'http://tvimages.burrp.com/images/channels1/spiritual/Aseervatham-TV.png','category'=>'devotional'),
			array('name'=>'Bhakti TV','id'=>386,'logo'=>'http://tvimages.burrp.com/images/channels1/spiritual/Bhakti-TV.png','category'=>'devotional'),
			array('name'=>'Divya Tv','id'=>345,'logo'=>'http://tvimages.burrp.com/images/channels1/spiritual/divya-tv.png','category'=>'devotional'),
			array('name'=>'God Tv','id'=>369,'logo'=>'http://tvimages.burrp.com/images/channels1/Spiritual/GOD-Tv.png','category'=>'devotional'),
			array('name'=>'Ishwar Tv','id'=>324,'logo'=>'http://tvimages.burrp.com/images/channels1/spiritual/Ishwar-Tv.png','category'=>'devotional'),
			array('name'=>'MY TV','id'=>333,'logo'=>'http://tvimages.burrp.com/images/channels1/spiritual/MY-TV.png','category'=>'devotional'),
			array('name'=>'Soham TV','id'=>355,'logo'=>'http://tvimages.burrp.com/images/channels1/spiritual/Soham-TV.png','category'=>'devotional'),

			array('name'=>'DD Sports','id'=>176,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/DD-Sports.png','category'=>'sports'),
			array('name'=>'Neo Prime','id'=>100,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/Neo-Prime.png','category'=>'sports'),
			array('name'=>'Neo Sports','id'=>49,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/Neo-Sports.png','category'=>'sports'),
			array('name'=>'Sony Six','id'=>282,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/Sony-Six.png','category'=>'sports'),
			array('name'=>'Sony Six HD','id'=>496,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/Sony-Six-HD.png','category'=>'sports'),
			array('name'=>'Star Sports 1','id'=>102,'logo'=>'http://tvimages.burrp.com/images/channels1/Sports/starsports-1.png','category'=>'sports'),
			array('name'=>'Star Sports 2','id'=>513,'logo'=>'http://tvimages.burrp.com/images/channels1/Sports/starsports-2.png','category'=>'sports'),
			array('name'=>'Star Sports 3','id'=>103,'logo'=>'http://tvimages.burrp.com/images/channels1/Sports/starsports-3.png','category'=>'sports'),
			array('name'=>'Star Sports 4','id'=>101,'logo'=>'http://tvimages.burrp.com/images/channels1/Sports/starsports-4.png','category'=>'sports'),
			array('name'=>'Ten Action','id'=>154,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/Ten-Action.png','category'=>'sports'),
			array('name'=>'Ten Cricket','id'=>186,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/Ten-Cricket.png','category'=>'sports'),
			array('name'=>'Ten Golf','id'=>269,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/Ten-Golf.png','category'=>'sports'),
			array('name'=>'Ten HD','id'=>314,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/Ten-HD.png','category'=>'sports'),
			array('name'=>'Ten Sports','id'=>105,'logo'=>'http://tvimages.burrp.com/images/channels1/sports/Ten-Sports.png','category'=>'sports'),

			);

foreach($channels as $channel)
{
	DB::table('channels')->insert(
		array('id'=>$channel['id'], 'channel_name' => $channel['name'], 'channel_logo'=>$channel['logo'], 'channel_category'=>$channel['category'])
		);
}

}

}